Enumerable methods rebuilt
flpfar/enumerable-methods pull request #3
Opened 2020-04-01 16:13 UTC by flpfar

This branch includes the following:

- The rewritten methods: my_each, my_each_with_index, my_select, my_all?, my_any?, my_none?, my_count, my_map, my_inject and multiply_els.
- Rubocop and stickler linter files
- Appropriate readme file

2020-04-01 19:22 UTC, kobiyoyo requested changes
## Hi @flpfar    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 


- [x] `my_inject`:
- Combines all elements of enum by applying a binary operation, specified by a block:
 `p (1..5).my_inject(4) { |prod, n| prod * n }` should return 480










### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-01 20:59 UTC, flpfar commented
Thank you for reviewing my code, @kobiyoyo! Problem with my_inject fixed!

2020-04-02 12:03 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @flpfar :handshake: 

### Thank you for doing the changes requested by the previous reviewer, :medal_sports:  you can merge this branch :heavy_check_mark: 

### I've left some optional changes in the comments on your code bellow :point_down: 

PROJECT STATUS: APPROVED :green_apple:

2020-04-02 12:03 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]

#### my_map 

- [x] in the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block were given, only execute the proc. The real map doesn't have this feature, but you were asked to have it so I strongly recommend to have it
Given 
```ruby
my_proc = Proc.new {|num| num > 10 }
```
Result
```ruby
puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  => true true false false
```

2020-04-02 12:03 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]

- [x] I strongly recommend to put the method mutiply_els in a different module because is not an Enumerable method

2020-04-02 12:03 UTC, euqueme commented on main.rb
> +  end
[OPTIONAL]

#### my_none?

I think we could get the block of my_none? from my_any? we should only do something like !my_any? for my_none? to work. For example:

  def my_none?(arg = nil, &block)
    !my_any?(arg = nil,&block)
  end

To make this work we have to use block.call(element) instead of yield(element) in my_any?

2020-04-02 15:30 UTC, flpfar commented
I really appreciated your review, @euqueme! The optional changes you gave me are concise and made my code look much better! I've implemented them already. Thank you very much! :+1:

2020-04-02 15:31 UTC, merged